### ISSUE TITLE
No configuration window

### ISSUE THREAD

**Issue by Pant** [ente76/guillotine#6]
I press the configuration window and nothing happens.

Linux Anonymous 5.12.13-arch1-1 #1 SMP PREEMPT Wed, 23 Jun 2021 16:19:29 +0000 x86_64 GNU/Linux
gnome-shell-1:40.3-1
Arch Linux on Wayland.

**Comment by ente76** [comment]
Could you please elaborate? Do you mean the configuration option in the default configuration? That is depending on a working xdg-open and a valid configuration for text files.

you can edit the configuration manually in ~/.config/guillotine.json. Use the default shown in the documentation as a starting point.

**Comment by Pant** [comment]
I was expecting a windows with configuration options, not an editor with the `~/.config/guillotine.json`.

My bad, Closing this issue
