### ISSUE TITLE
Error installing in Ubuntu 21.10 + Gnome 40.4.0

### ISSUE THREAD

**Issue by fabricio-godoi** [ente76/guillotine#9]
Greetings!

I've tried to update to the latest version in Ubuntu 21.10 + Gnome 40.4.0, and it could not be updated. I had to roll back manually to v7 to work with my distro (did not test v8).

Thanks!

**Comment by ente76** [comment]
Version 8 will probably make no difference to version 9. The change from 8 to 9 was rather minor.

Unfortunately your error report is too vague to have a chance to analyze to issue. Please install the latest version and when it fails run `journalctl -f GNOME_SHELL_EXTENSION_UUID=guillotine@fopdoodle.net` and `journalctl -f _COMM=gnome-shell`. Provide the output of that output so I can have a closer look.

**Comment by ente76** [comment]
The issue has been closed due to a lack of error details.
